### ISSUE TITLE
AccessDenied for image on home page of paste up

### ISSUE THREAD

**Issue by obrienm** [guardian/pasteup#6]
Go to the paste up home page:

http://pasteup.s3.amazonaws.com/docs/index.html

Look at the right hand column, you'll see an image that cannot be loaded, under 'Getting started'.

The image's URL is:

http://pasteup.s3.amazonaws.com/img/code.jpg

Which is giving me an 'access is denied' error, HTTP status code 403.

**Comment by SiAdcock** [comment]
Closing as this page no longer exists
